blueprint:
  name: Gestion complète UPS Eaton / Homelab (Blueprint)
  description: >
    Notifications UPS + arrêt automatique du homelab + boutons mobiles.
    Version Blueprint entièrement configurable, avec détection automatique
    des entités UPS via une entité de référence.
  domain: automation

  input:

    # --- Configuration UPS ---
    configuration_ups:
      name: "1 - Configuration de l'UPS"
      description: "Paramètres de votre UPS."
      icon: mdi:toolbox-outline
      collapsed: false
      input:
        ups_state_code:
          name: État UPS (code d’état)
          description: Entité permettant de détecter OB / OL / ALARM.
          selector:
            entity:
              domain: sensor

        ups_runtime:
          name: Autonomie UPS (en secondes)
          description: Entité définissant l’autonomie restante (en secondes).
          selector:
            entity:
              domain: sensor

        ups_state_text:
          name: État UPS (texte)
          description: Entité texte décrivant l’état de l’UPS.
          selector:
            entity:
              domain: sensor


    # --- Notifications ---
    configuration_notifications:
      name: "2 - Configuration notifications App Compagnon"
      description: "Service de notification via l'application mobile Compagnon."
      icon: mdi:checkbox-blank-badge
      collapsed: true
      input:
        notify_mobile:
          name: "Service de notification mobile"
          description: >
            Service utilisé pour la notification.<br/>
            (ex :  `notify.mobile_app_sm_s928b`)
          selector:
            text:

        notif_channel:
          name: Canal Android (optionnel)
          description: "Canal de notification préféré. Il faut créer en amont le canal s'il est nouveau !"
          default: "UPS_channel"
          selector:
            text:

    # --- Configuration élaborée ---
    configuration_shell:
      name: "3 - Configuration spécifique"
      description: "Configuration des actions spécifiques."
      icon: mdi:wrench-clock
      collapsed: true
      input:
        shutdown_service:
          name: "Service d’arrêt du homelab"
          description: >
            Service (shell_command, script, etc.) déclenchant l’arrêt Proxmox.<br/>
            (ex : `shell_command.create_shutdown_file`)
          selector:
            text:

        critical_pattern:
          name: Codes d’état batterie critique
          description: >
            Texte exact de l'entité lors du passage en alarme.<br/>
            Par défaut : "ALARM OB OL"<br/>
            **Ne modifiez pas ce champ sauf exception !**
          default: "ALARM OB OL"
          selector:
            text:

        critical_delay:
          name: Durée avant arrêt critique (secondes)
          description: "Après le déclenchement de l'alarme au niveau bas (20%), délai supplémentaire avant le déclenchement de la phase critique."
          default: 30
          selector:
            number:
              min: 5
              max: 600
              unit_of_measurement: sec
              mode: slider

mode: single


# ======================================================
# ===                 AUTOMATION                     ===
# ======================================================

variables:

  # fallback
  critical_pattern: >
    {% if inputs.critical_pattern | trim == "" %}
      ALARM OB OL
    {% else %}
      {{ inputs.critical_pattern }}
    {% endif %}


# ======================================================
# ===                 TRIGGERS                       ===
# ======================================================

trigger:
  - id: OB_begin
    platform: state
    entity_id: !input ups_state_code
    to: "OB"
    for: "00:00:05"

  - id: autonomie_critique
    platform: state
    entity_id: !input ups_state_code
    to: !input critical_pattern
    for:
      seconds: !input critical_delay

  - id: courant_retour
    platform: state
    entity_id: !input ups_state_code
    to: "OL"

  - id: check_remaining
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: CHECK_REMAINING


# ======================================================
# ===                 ACTIONS                        ===
# ======================================================

action:
  - choose:

      # --- Coupure secteur ---
      - conditions:
          - condition: trigger
            id: OB_begin
        sequence:
          - service: !input notify_mobile
            data:
              title: "⚠️ Coupure électrique détectée"
              message: >-
                {% set s = states(blueprint.inputs.ups_runtime) | int(0) %}
                {% if s > 0 %}
                  {% set h = s // 3600 %}
                  {% set m = (s % 3600) // 60 %}
                  {% set sec = s % 60 %}
                  {% set end = (now() + timedelta(seconds=s)).strftime("%H:%M:%S") %}
                  L'UPS est sur batterie depuis plus de 30 secondes.  
                  **Autonomie restante : {{ "%02d:%02d:%02d" | format(h, m, sec) }}**  
                  **Extinction estimée à : {{ end }}**
                {% else %}
                  L'UPS est sur batterie depuis plus de 30 secondes.  
                  Autonomie inconnue.
                {% endif %}
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high
                actions:
                  - action: CHECK_REMAINING
                    title: Vérifier autonomie
                  - action: FORCE_SHUTDOWN
                    title: Forcer arrêt du homelab

      # --- Autonomie critique ---
      - conditions:
          - condition: trigger
            id: autonomie_critique
        sequence:
          - service: !input notify_mobile
            data:
              title: "⛔ Arrêt automatique homelab"
              message: >-
                Batterie critique détectée (`{{ states(blueprint.inputs.ups_state_code) }}`).  
                Extinction immédiate et propre du homelab.
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high

          - delay:
              seconds: !input critical_delay

          - service: !input shutdown_service

      # --- Courant rétabli ---
      - conditions:
          - condition: trigger
            id: courant_retour
        sequence:
          - service: !input notify_mobile
            data:
              title: "🔌 Courant rétabli"
              message: >
                L'alimentation secteur est revenue.  
                L'UPS fonctionne normalement.
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high

      # --- Bouton "Check autonomie" ---
      - conditions:
          - condition: trigger
            id: check_remaining
        sequence:
          - service: !input notify_mobile
            data:
              title: "🔍 Autonomie actuelle"
              message: >-
                {% set s = states(blueprint.inputs.ups_runtime) | int(0) %}
                {% if s > 0 %}
                  {% set h = s // 3600 %}
                  {% set m = (s % 3600) // 60 %}
                  {% set sec = s % 60 %}
                  {% set end = (now() + timedelta(seconds=s)).strftime("%H:%M:%S") %}
                  Check-in.  
                  **Autonomie : {{ "%02d:%02d:%02d" | format(h, m, sec) }}**  
                  **Extinction estimée : {{ end }}**
                {% else %}
                  **Autonomie : inconnue**
                {% endif %}
                **État UPS :** {{ states(blueprint.inputs.ups_state_text) }}
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high
                actions:
                  - action: FORCE_SHUTDOWN
                    title: Forcer arrêt du homelab
