blueprint:
  name: Gestion complète UPS Eaton / Homelab (Blueprint)
  description: >
    Notifications UPS + arrêt automatique du homelab + boutons mobiles.
    Version Blueprint entièrement configurable.
  domain: automation
  input:

    configuration_ups:
      name: "1 - Configuration de l'UPS"
      description: "Paramètres de votre UPS."
      icon: mdi:toolbox-outline
      collapsed: false
      input:

        ups_base:
          name: "Entité de base UPS"
          description: "Exemple : sensor.eaton3s"
          selector:
            entity:
              filter:
                - domain: sensor

        ups_runtime:
          name: Autonomie UPS (en secondes)
          description: Entité contenant l’autonomie restante en secondes.
          selector:
            entity:
              filter:
                - domain: sensor

        ups_human_state:
          name: État UPS (texte)
          description: Entité texte décrivant l’état de l’UPS.
          selector:
            entity:
              filter:
                - domain: sensor

        critical_pattern:
          name: Codes d’état batterie critique
          description: >
            Texte de l'entité lors du passage en alarme.<br/>
            Par défaut : "ALARM OB OL"
          default: "ALARM OB OL"
          selector:
            text:

        critical_delay:
          name: Durée avant arrêt critique (secondes)
          default: 30
          selector:
            number:
              min: 5
              max: 600
              unit_of_measurement: sec
              mode: slider

    configuration_notifications:
      name: "2 - Configuration notifications App Comagnon"
      description: "Service de notification via l'application mobile Compagnon."
      icon: mdi:checkbox-blank-badge
      collapsed: true
      input:

        mobile_notify:
          name: Service de notification mobile
          description: Service `notify.xxx` pour envoyer les messages.
          selector:
            action:

        shutdown_service:
          name: Service d’arrêt du homelab
          description: Service (shell_command, script, etc.) qui déclenche l’arrêt Proxmox.
          selector:
            action:

mode: single

trigger:
  - id: coupure_30s
    platform: state
    entity_id: "{{ blueprint.inputs.ups_base }}_code_d_etat"
    to: "OB"
    for: "00:00:05"

  - id: autonomie_critique
    platform: state
    entity_id: "{{ blueprint.inputs.ups_base }}_code_d_etat"
    to: !input critical_pattern
    for:
      seconds: !input critical_delay

  - id: courant_retour
    platform: state
    entity_id: "{{ blueprint.inputs.ups_base }}_code_d_etat"
    to: "OL"

  - id: check_remaining
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: CHECK_REMAINING

action:
  - choose:

      - conditions:
          - condition: trigger
            id: coupure_30s
        sequence:
          - alias: "Notification coupure électrique"
            service: !input mobile_notify
            data:
              title: ⚠️ Coupure électrique détectée
              message: >-
                {% set s = states(blueprint.inputs.ups_runtime) | int(0) %}
                {% if s > 0 %}
                  {% set h = s // 3600 %}
                  {% set m = (s % 3600) // 60 %}
                  {% set sec = s % 60 %}
                  {% set end = (now() + timedelta(seconds=s)).strftime("%H:%M:%S") %}
                  L'UPS est sur batterie depuis plus de 30 secondes.  
                  **Autonomie restante : {{ "%02d:%02d:%02d" | format(h, m, sec) }}**  
                  **Extinction estimée à : {{ end }}**
                {% else %}
                  L'UPS est sur batterie depuis plus de 30 secondes.  
                  Autonomie inconnue.
                {% endif %}
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high
                actions:
                  - action: CHECK_REMAINING
                    title: Vérifier l'autonomie
                  - action: FORCE_SHUTDOWN
                    title: Forcer l'arrêt du homelab

      - conditions:
          - condition: trigger
            id: autonomie_critique
        sequence:
          - alias: "Alerte critique + arrêt"
            service: !input mobile_notify
            data:
              title: ⛔ Arrêt automatique homelab
              message: >-
                Niveau batterie critique détecté (`{{ states(blueprint.inputs.ups_base ~ "_code_d_etat") }}`).  
                Extinction immédiate et propre du homelab.
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high
          - delay:
              seconds: !input critical_delay
          - alias: "Lancement arrêt"
            service: !input shutdown_service

      - conditions:
          - condition: trigger
            id: courant_retour
        sequence:
          - alias: "Courant rétabli"
            service: !input mobile_notify
            data:
              title: 🔌 Courant rétabli
              message: >
                L'alimentation secteur est revenue.  
                L'UPS fonctionne normalement.
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high

      - conditions:
          - condition: trigger
            id: check_remaining
        sequence:
          - alias: "Check autonomie manuelle"
            service: !input mobile_notify
            data:
              title: 🔍 Autonomie actuelle
              message: >-
                {% set s = states(blueprint.inputs.ups_runtime) | int(0) %}
                {% if s > 0 %}
                  {% set h = s // 3600 %}
                  {% set m = (s % 3600) // 60 %}
                  {% set sec = s % 60 %}
                  {% set end = (now() + timedelta(seconds=s)).strftime("%H:%M:%S") %}
                  Check-in.  
                  **Autonomie : {{ "%02d:%02d:%02d" | format(h, m, sec) }}**  
                  **Extinction estimée : {{ end }}**
                {% else %}
                  **Autonomie : inconnue**
                {% endif %}  
                **État UPS :** {{ states(blueprint.inputs.ups_human_state) }}
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high
                actions:
                  - action: FORCE_SHUTDOWN
                    title: Forcer l'arrêt du homelab
