blueprint:
  name: Gestion complète UPS Eaton / Homelab (Blueprint)
  description: >
    Notifications UPS + arrêt automatique du homelab + boutons mobiles.
    Version Blueprint entièrement configurable, avec détection automatique
    des entités UPS via une entité de référence.
  domain: automation

  input:

    # --- Configuration UPS ---
    configuration_ups:
      name: "1 - Configuration de l'UPS"
      description: "Paramètres de votre UPS."
      icon: mdi:toolbox-outline
      collapsed: false
      input:
        ups_state_code:
          name: Code d'état
          description: >
            Entité permettant de détecter OB / OL / ALARM.<br/>
            Défaut : "Code d'état"<br/>
            (ex : `sensor.eaton3s_code_d_etat`)
          default: "sensor.eaton3s_code_d_etat"
          selector:
            entity:
              domain: sensor

        ups_runtime:
          name: Autonomie de la batterie
          description: >
            Entité définissant l'autonomie restante (en secondes).<br/>
            Défaut : "Autonomie de la batterie"<br/>
            (ex: `sensor.eaton3s_autonomie_de_la_batterie`)
          default: "sensor.eaton3s_autonomie_de_la_batterie"
          selector:
            entity:
              domain: sensor

        ups_state_text:
          name: État
          description: >
            Entité texte décrivant l'état de l'UPS.<br/>
            Défaut : "État"<br/>
            (ex : `sensor.eaton3s_etat`)
          default: "sensor.eaton3s_etat"
          selector:
            entity:
              domain: sensor

    # --- Notifications ---
    configuration_notifications:
      name: "2 - Configuration notifications App Compagnon"
      description: "Service de notification via l'application mobile Compagnon."
      icon: mdi:checkbox-blank-badge
      collapsed: true
      input:
        notify_mobile:
          name: "Service de notification mobile"
          description: >
            Service utilisé pour la notification.<br/>
            (ex :  `notify.mobile_app_sm_s928b`)
          default: "notify.mobile_app_sm_s928b"
          selector:
            text:

        notif_channel:
          name: Canal Android (optionnel)
          description: "Canal de notification préféré. Il faut créer en amont le canal s'il est nouveau !"
          default: "UPS_channel"
          selector:
            text:

    # --- Configuration spécifique ---
    configuration_shell:
      name: "3 - Configuration spécifique"
      description: "Configuration des actions spécifiques."
      icon: mdi:wrench-clock
      collapsed: true
      input:
        shutdown_service:
          name: "Service d'arrêt du homelab"
          description: >
            Service (shell_command, script, etc.) déclenchant l'arrêt Proxmox.<br/>
            (ex : `shell_command.create_shutdown_file`)
          default: "shell_command.create_shutdown_file"
          selector:
            text:

        critical_pattern:
          name: Codes d'état batterie critique
          description: >
            Texte exact de l'entité lors du passage en alarme.<br/>
            Par défaut : "ALARM OB OL"<br/>
            **Ne modifiez pas ce champ sauf exception !**
          default: "ALARM OB OL"
          selector:
            text:

        critical_delay:
          name: Durée avant arrêt critique (secondes)
          description: "Après le déclenchement de l'alarme au niveau bas (20%), délai supplémentaire avant le déclenchement de la phase critique."
          default: 30
          selector:
            number:
              min: 5
              max: 600
              unit_of_measurement: sec
              mode: slider

mode: single

variables:
  v_input_ups_runtime: !input ups_runtime
  v_input_ups_state_text: !input ups_state_text
  v_input_ups_state_code: !input ups_state_code
  v_notify_mobile: !input notify_mobile
  v_notif_channel: !input notif_channel
  v_shutdown_service: !input shutdown_service
  v_critical_delay: !input critical_delay

trigger:
  - id: OB_begin
    platform: state
    entity_id: !input ups_state_code
    to: "OB"
    for: "00:00:05"

  - id: autonomie_critique
    platform: state
    entity_id: !input ups_state_code
    to: !input critical_pattern
    for:
      seconds: !input critical_delay

  - id: courant_retour
    platform: state
    entity_id: !input ups_state_code
    to: "OL"

  - id: check_remaining
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: CHECK_REMAINING

action:
  - choose:

      # --- Coupure secteur ---
      - conditions:
          - condition: trigger
            id: OB_begin
        sequence:
          - service: !input notify_mobile
            data:
              title: "⚠️ Coupure électrique détectée"
              message: >
                {% set s = states[v_input_ups_runtime] | int(0) %}
                {% if s > 0 %}
                  {% set h = s // 3600 %}
                  {% set m = (s % 3600) // 60 %}
                  {% set sec = s % 60 %}
                  {% set end = (now() + timedelta(seconds=s)).strftime("%H:%M:%S") %}
                  L'UPS est sur batterie.  
                  **Autonomie restante : {{ "%02d:%02d:%02d"|format(h, m, sec) }}**  
                  **Extinction estimée à : {{ end }}**
                {% else %}
                  L'UPS est sur batterie depuis plus de 30 secondes.  
                  Autonomie inconnue.
                {% endif %}
              sticky: true
              channel: !input notif_channel
              importance: high
              priority: high
              actions:
                - action: CHECK_REMAINING
                  title: Vérifier autonomie
                - action: FORCE_SHUTDOWN
                  title: Forcer arrêt du homelab

      # --- Autonomie critique ---
      - conditions:
          - condition: trigger
            id: autonomie_critique
        sequence:
          - service: !input notify_mobile
            data:
              title: "⛔ Arrêt automatique homelab"
              message: >-
                Batterie critique détectée (`{{ states(v_input_ups_state_code) }}`).  
                Extinction immédiate et propre du homelab.
              sticky: true
              channel: !input notif_channel
              importance: high
              priority: high

          - delay:
              seconds: !input critical_delay

          - service: !input shutdown_service