blueprint:
  name: Gestion complète UPS Eaton / Homelab (Blueprint)
  description: >
    Notifications UPS + arrêt automatique du homelab + boutons mobiles.
    Version Blueprint entièrement configurable, avec détection automatique
    des entités UPS via une entité de référence.
  domain: automation

  input:

    configuration_ups:
      name: "1 - Configuration de l'UPS"
      description: "Paramètres de votre UPS."
      icon: mdi:toolbox-outline
      collapsed: false
      input:

        ups_reference:
          name: Entité de référence UPS
          description: >
            Sélectionnez n'importe quelle entité du même ensemble UPS<br/>
            (ex : `sensor.eaton3s_type_d_ups`).
          selector:
            entity:
              filter:
                - domain: sensor



    configuration_notifications:
      name: "2 - Configuration notifications App Compagnon"
      description: "Service de notification via l'application mobile Compagnon."
      icon: mdi:checkbox-blank-badge
      collapsed: true
      input:

        notify_mobile:
          name: "Service de notification mobile"
          description: >
            Service utilisé pour la notification.<br/>
            (ex :  `notify.mobile_app_sm_s928b`)
          selector:
            text:

    configuration_shell:
      name: "3 - Configuration spécifique"
      description: "Configuration des actions spécifiques."
      icon: mdi:wrench-clock
      collapsed: true
      input:

        shutdown_service:
          name: "Service d’arrêt du homelab"
          description: "Service (shell_command, script, etc.) déclenchant l’arrêt Proxmox."
          selector:
            action:

        critical_pattern:
          name: Codes d’état batterie critique
          description: >
            Texte exact de l'entité lors du passage en alarme.<br/>
            Par défaut : "ALARM OB OL"
          default: "ALARM OB OL"
          selector:
            text:

        critical_delay:
          name: Durée avant arrêt critique (secondes)
          description: "Après le déclenchement de l'alarme au niveau bas (20%), délai supplémentaire avant le déclenchement de la phase critique."
          default: 30
          selector:
            number:
              min: 5
              max: 600
              unit_of_measurement: sec
              mode: slider

mode: single

variables:

  # Extraction automatique du préfixe UPS
  ups_base: >
    {% set ref = inputs.ups_reference %}
    {% set parts = ref.split('_') %}
    {{ parts[0] ~ "_" ~ parts[1] }}

  ups_code: "{{ ups_base ~ '_code_d_etat' }}"
  ups_runtime: "{{ ups_base ~ '_autonomie_de_la_batterie' }}"
  ups_human: "{{ ups_base ~ '_etat' }}"

trigger:
  - id: coupure_30s
    platform: state
    entity_id: "{{ ups_code }}"
    to: "OB"
    for: "00:00:05"

  - id: autonomie_critique
    platform: state
    entity_id: "{{ ups_code }}"
    to: !input critical_pattern
    for:
      seconds: !input critical_delay

  - id: courant_retour
    platform: state
    entity_id: "{{ ups_code }}"
    to: "OL"

  - id: check_remaining
    platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: CHECK_REMAINING

action:
  - choose:

      # --- Coupure secteur ---
      - conditions:
          - condition: trigger
            id: coupure_30s
        sequence:
          - service: !input notify_mobile
            data:
              title: "⚠️ Coupure électrique détectée"
              message: >-
                {% set s = states(ups_runtime) | int(0) %}
                {% if s > 0 %}
                  {% set h = s // 3600 %}
                  {% set m = (s % 3600) // 60 %}
                  {% set sec = s % 60 %}
                  {% set end = (now() + timedelta(seconds=s)).strftime("%H:%M:%S") %}
                  L'UPS est sur batterie depuis plus de 30 secondes.  
                  **Autonomie restante : {{ "%02d:%02d:%02d" | format(h, m, sec) }}**  
                  **Extinction estimée à : {{ end }}**
                {% else %}
                  L'UPS est sur batterie depuis plus de 30 secondes.  
                  Autonomie inconnue.
                {% endif %}
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high
                actions:
                  - action: CHECK_REMAINING
                    title: Vérifier autonomie
                  - action: FORCE_SHUTDOWN
                    title: Forcer arrêt du homelab

      # --- Autonomie critique ---
      - conditions:
          - condition: trigger
            id: autonomie_critique
        sequence:
          - service: !input notify_mobile
            data:
              title: "⛔ Arrêt automatique homelab"
              message: >-
                Batterie critique détectée (`{{ states(ups_code) }}`).  
                Extinction immédiate et propre du homelab.
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high

          - delay:
              seconds: !input critical_delay

          - service: !input shutdown_service

      # --- Courant rétabli ---
      - conditions:
          - condition: trigger
            id: courant_retour
        sequence:
          - service: !input notify_mobile
            data:
              title: "🔌 Courant rétabli"
              message: >
                L'alimentation secteur est revenue.  
                L'UPS fonctionne normalement.
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high

      # --- Bouton "Check autonomie" ---
      - conditions:
          - condition: trigger
            id: check_remaining
        sequence:
          - service: !input notify_mobile
            data:
              title: "🔍 Autonomie actuelle"
              message: >-
                {% set s = states(ups_runtime) | int(0) %}
                {% if s > 0 %}
                  {% set h = s // 3600 %}
                  {% set m = (s % 3600) // 60 %}
                  {% set sec = s % 60 %}
                  {% set end = (now() + timedelta(seconds=s)).strftime("%H:%M:%S") %}
                  Check-in.  
                  **Autonomie : {{ "%02d:%02d:%02d" | format(h, m, sec) }}**  
                  **Extinction estimée : {{ end }}**
                {% else %}
                  **Autonomie : inconnue**
                {% endif %}
                **État UPS :** {{ states(ups_human) }}
              data:
                sticky: true
                channel: UPS Alerts
                importance: high
                priority: high
                actions:
                  - action: FORCE_SHUTDOWN
                    title: Forcer arrêt du homelab
